import { state } from './store.js';
import { packageAssets } from './packaging.js';

const README = `This zip is a ready-to-publish static website generated by the PDF Book
Website workstation.

To publish on GitHub Pages:
1. Create a new GitHub repository (or use an existing one).
2. Unzip this archive and commit its contents to the repository root
   (index.html should sit at the repo root, not inside a subfolder).
3. Push to GitHub.
4. In the repository, go to Settings -> Pages, set "Source" to your default
   branch and folder "/ (root)", then save.
5. GitHub will publish the site at https://<user>.github.io/<repo>/ within
   a minute or two.

You can also just open index.html through any static file server locally
to preview it (a plain double-click / file:// URL will not work because
the page loads book.json and its own scripts as modules, which browsers
block on file:// for security reasons).
`;

function setStatus(text) {
  const el = document.getElementById('statusText');
  if (el) el.textContent = text;
}

async function fetchText(path) {
  const res = await fetch(path);
  if (!res.ok) throw new Error(`Failed to load ${path} (${res.status})`);
  return res.text();
}

export async function exportWebsite() {
  setStatus('Building website export…');

  const [indexHtml, viewerCss, viewerJs, pageFlipLib, schemaJs, rendererJs, paginationJs] = await Promise.all([
    fetchText('../viewer/index.html'),
    fetchText('../viewer/viewer.css'),
    fetchText('../viewer/viewer.js'),
    fetchText('../viewer/lib/page-flip.browser.js'),
    fetchText('../shared/schema.js'),
    fetchText('../shared/renderer.js'),
    fetchText('../shared/pagination.js'),
  ]);

  // In the dev tree, viewer/viewer.js sits next to shared/ (as a sibling
  // of the viewer/ folder), so it imports via '../shared/...'. In the
  // exported bundle, viewer.js lives at the bundle root with shared/ as
  // its own direct sibling, so the import needs to be './shared/...'.
  const rewrittenViewerJs = viewerJs.replace(/\.\.\/shared\//g, './shared/');

  const { bookJson, files } = packageAssets(state.book);

  const zip = new JSZip();
  zip.file('index.html', indexHtml);
  zip.file('viewer.css', viewerCss);
  zip.file('viewer.js', rewrittenViewerJs);
  zip.file('lib/page-flip.browser.js', pageFlipLib);
  zip.file('shared/schema.js', schemaJs);
  zip.file('shared/renderer.js', rendererJs);
  zip.file('shared/pagination.js', paginationJs);
  zip.file('book.json', JSON.stringify(bookJson, null, 2));
  zip.file('README.txt', README);
  for (const f of files) zip.file(f.path, f.blob);

  const blob = await zip.generateAsync({ type: 'blob' });
  const name = (state.book.title || 'book').replace(/[^a-zA-Z0-9_.-]/g, '_');
  saveAs(blob, `${name}-website.zip`);
  setStatus('Website exported.');
}
